# Generated by Django 4.1 on 2024-05-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_client_options_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('archived', 'Archived'), ('active', 'Active')], default='active', max_length=255),
        ),
    ]
