# Generated by Django 4.1 on 2024-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints_test', '0002_alter_actor_age_alter_actor_death_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='death_year',
            field=models.IntegerField(null=True),
        ),
    ]
