# Generated by Django 4.1 on 2024-05-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints_test', '0003_alter_actor_age_alter_actor_death_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
